version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    env_file: .env
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--js"
      - "--http_port=8222"
    restart: unless-stopped

  nats-box:
    image: synadia/nats-box:latest
    container_name: nats-box
    stdin_open: true
    tty: true
    depends_on:
      - nats

volumes:
  mongo_db:
