apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-deployment
  labels:
    app: domain
spec:
  replicas: 4
  selector:
    matchLabels:
      app: domain
  template:
    metadata:
      labels:
        app: domain
    spec:
      containers:
        - name: domain
          image: domain:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: domain-configmap
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: domain-configmap
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: domain-configmap
                  key: db_name
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  name: domain-configmap
                  key: nats_uri
