apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i-ingress

spec:
  ingressClassName: nginx
  rules:
    - host: delivery-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: delivery-app-service
                port:
                  number: 8080
