spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${HOST}:${PORT}/${DB_NAME}?authSource=admin
  kafka:
    bootstrap-servers: http://localhost:9092
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10

nats.uri: ${NATS_URI}

server:
  servlet:
    contextPath: /api/v1

mongock:
  migration-scan-package: com.example.delivery.config
