spring:
  data:
    mongodb:
      uri: mongodb://${HOST}:${PORT}/${DB_NAME}

nats.uri: ${NATS_URI}

server:
  servlet:
    contextPath: /api/v1

mongock:
  migration-scan-package: com.example.delivery.config
